# Generated by Django 6.0.7 on 2026-07-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_order_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
    ]
